# Generated by Django 5.1 on 2024-08-15 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenda_cultural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
